### ISSUE TITLE
Tạo các bảng trong QLBH Database

### ISSUE THREAD

**Issue by NguynThien** [NguynThien/Nhom2HQTCSDL#1]

**Comment by NguynThien** [comment]
[SQL_QLBH_create_table.zip](https://github.com/NguynThien/Nhom2HQTCSDL/files/10046630/SQL_QLBH_create_table.zip)

**Comment by NguynTinh** [comment]
Đã kiểm tra #

**Comment by NguynThien** [comment]
Dã hoàn thành
