### ISSUE TITLE
Tạo các bảng trong QLGV Database

### ISSUE THREAD

**Issue by NguynThien** [NguynThien/Nhom2HQTCSDL#2]

**Comment by NguynThien** [comment]
[SQL_QLGV_create_table.zip](https://github.com/NguynThien/Nhom2HQTCSDL/files/10046635/SQL_QLGV_create_table.zip)

**Comment by NguynTinh** [comment]
Làm thiếu bảng giáo viên 
create table GIAOVIEN
(
MAGV char(4) Primary Key,
HOTEN varchar(40),
HOCVI varchar(10),
HOCHAM varchar(10),
GIOITINH varchar(3),
NGSINH SMALLDATETIME,
NGVL SMALLDATETIME,
HESO numeric(4,2),
MUCLUONG money,
MAKHOA varchar(4),
)

**Comment by NguynThien** [comment]
[SQL_QLGV_create_table.zip](https://github.com/NguynThien/Nhom2HQTCSDL/files/10046689/SQL_QLGV_create_table.zip)

Updated
