### ISSUE TITLE
Nhập dữ liệu các bảng QLGV

### ISSUE THREAD

**Issue by NguynThien** [NguynThien/Nhom2HQTCSDL#4]

**Comment by NguynTinh** [comment]
[QLGV.zip](https://github.com/NguynThien/Nhom2HQTCSDL/files/10046611/QLGV.zip)

**Comment by LThienPhuc** [comment]
[QLGV.zip](https://github.com/NguynThien/Nhom2HQTCSDL/files/10046636/QLGV.zip)

**Comment by NguynTinh** [comment]
Thêm bảng khoa
insert into KHOA(MAKHOA, TENKHOA,NGTLAP, TRGKHOA) 
values ('KHMT', 'Khoa hoc may tinh', 7/6/2005, 'GV01')
insert into  KHOA(MAKHOA, TENKHOA,NGTLAP, TRGKHOA) 
values ('HTTT', 'He thong thong tin', 7/6/2005,'GV02')
insert into KHOA(MAKHOA, TENKHOA,NGTLAP, TRGKHOA) 
values ('CNPM', 'Cong nghe phan mem', 7/6/2005, 'GV04')
insert into KHOA(MAKHOA, TENKHOA,NGTLAP, TRGKHOA) 
values ('MTT', 'Mang va truyen thong', 20/10/2005, 'GV03')
insert into KHOA(MAKHOA, TENKHOA,NGTLAP, TRGKHOA) 
values ('KTMT','Ky thuat may tinh', 20/12/2005, 'Null')

**Comment by NguynThien** [comment]
OK, để update lại

**Comment by NguynThien** [comment]
[SQLQuery Khoa update.txt](https://github.com/NguynThien/Nhom2HQTCSDL/files/10046715/SQLQuery.Khoa.update.txt)

**Comment by NguynThien** [comment]
OK. Đã kiểm tra
